# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build',
         '--builder=gcr.io/buildpacks/builder',
         '--publish', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/app:$BUILD_ID']
  id: Build and package go app
# - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
#   args:
#       [
#         "deploy", "releases", "create", "release-$_RELEASE_TIMESTAMP",
#         "--delivery-pipeline", "cloud-run-pipeline",
#         "--region", "${_REGION}",
#         "--images", "app=${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/app:$BUILD_ID"
#       ]
#   entrypoint: gcloud
- name: 'google/cloud-sdk:latest'
  args:
  - -xe
  - -c
  - |
    gcloud config set deploy/region ${_REGION}
    sed -i s/PROJECT_ID/${PROJECT_ID}/g deploy/cloudrun/*
    gcloud deploy apply --file  deploy/clouddeploy.yaml
    gcloud deploy releases create rel-${SHORT_SHA} \
      --delivery-pipeline cloud-run-pipeline \
      --region ${_REGION} \
      --description "$(git log -1 --pretty='%s')" \
      --images app=${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers-repo/app:$BUILD_ID
  entrypoint: 'sh'